import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1' # Prevent local Windows DLL locking issues

import torch
import joblib

PTH_FILE = "ml/autoencoder.pth"
SCALER_FILE = "ml/models/scaler.save" # Wait, earlier I found it under ml/models/scaler.save via list_dir
STATS_FILE = "ml/model_stats.txt"
HEADER_FILE = "firmware/src/nn_weights.h"

def export_weights():
    print(f"Loading {PTH_FILE}...")
    model_state = torch.load(PTH_FILE, map_location='cpu')
    
    print(f"Loading {SCALER_FILE}...")
    scaler = joblib.load(SCALER_FILE)
    
    print(f"Loading {STATS_FILE}...")
    threshold = 0.5
    if os.path.exists(STATS_FILE):
        with open(STATS_FILE, "r") as f:
            for line in f:
                if "THRESHOLD_MSE" in line:
                    threshold = float(line.split("=")[1].strip())
    
    print(f"Writing to {HEADER_FILE}...")
    with open(HEADER_FILE, "w") as f:
        f.write("#ifndef NN_WEIGHTS_H\n")
        f.write("#define NN_WEIGHTS_H\n\n")
        f.write("// AUTO-GENERATED BY export_cpp_weights.py\n\n")
        
        # --- SCALER ---
        f.write("// Scaler Constants\n")
        f.write(f"const float SCALER_MEAN[4] = {{{scaler.mean_[0]:.6f}f, {scaler.mean_[1]:.6f}f, {scaler.mean_[2]:.6f}f, {scaler.mean_[3]:.6f}f}};\n")
        f.write(f"const float SCALER_SCALE[4] = {{{scaler.scale_[0]:.6f}f, {scaler.scale_[1]:.6f}f, {scaler.scale_[2]:.6f}f, {scaler.scale_[3]:.6f}f}};\n\n")
        
        # --- THRESHOLD ---
        f.write(f"const float ANOMALY_THRESHOLD = {threshold:.6f}f;\n\n")
        
        # --- WEIGHTS ---
        def write_tensor(name, tensor):
            flat = tensor.flatten().numpy()
            f.write(f"const float {name}[{len(flat)}] = {{")
            entries = [f"{val:.6f}f" for val in flat]
            f.write(", ".join(entries))
            f.write("};\n")
            
        write_tensor("ENC_L1_W", model_state["encoder.0.weight"])
        write_tensor("ENC_L1_B", model_state["encoder.0.bias"])
        f.write("\n")
        write_tensor("ENC_L2_W", model_state["encoder.2.weight"])
        write_tensor("ENC_L2_B", model_state["encoder.2.bias"])
        f.write("\n")
        write_tensor("DEC_L1_W", model_state["decoder.0.weight"])
        write_tensor("DEC_L1_B", model_state["decoder.0.bias"])
        f.write("\n")
        write_tensor("DEC_L2_W", model_state["decoder.2.weight"])
        write_tensor("DEC_L2_B", model_state["decoder.2.bias"])
        f.write("\n")

        f.write("#endif // NN_WEIGHTS_H\n")
        
    print("Done!")

if __name__ == "__main__":
    export_weights()
